l_korean:
 SETTING_DEBUG_SAVES:0 "디버그 저장 수"
 SETTING_TUTORIAL:0 "튜토리얼"
 SETTING_DISABLED_HINTS:0 "조언 비활성화"
 SETTING_FOCUS_ON_COMBAT:0 "전투 집중"
 SETTING_TOOLTIP_DELAY:1 "툴팁 지연 시간"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\n툴팁을 표시하기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "고정 해제 지연 시간"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n툴팁이 고정 해제되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_LOCK_TIME:0 "고정 지연 시간"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n툴팁이 고정되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "고정 후 열림 지연 시간"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n이미 다른 툴팁이 표시된 상태에서 툴팁이 고정되기까지 걸리는 지연 시간을 설정합니다."
 # Audio
 SETTING_Sound_Effects:1 "전체 효과음"
 SETTING_Sound_Effects_TOOLTIP:1 "#T 효과음 음량\n#!모든 효과음의 음량을 조절합니다."
 SETTING_Ambience:0 "환경음"
 SETTING_Ambience_TOOLTIP:1 "#T 환경음 음량\n#!환경음의 음량을 조절합니다."
 SETTING_TOOLTIP_MODE:1 "툴팁 모드"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\n툴팁 속의 툴팁을 이용할 수 있도록 툴팁의 "고정" 방식을 선택합니다."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "마우스 움직임"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\n마우스 커서를 밖으로 옮기기 전까지 툴팁이 그 자리에 자동으로 고정됩니다."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "행동 고정"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\n#V 마우스 가운데 버튼#!을 눌러 툴팁을 고정하거나 고정 해제합니다."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "시간 고정"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\n커서를 잠시 움직이지 않으면 툴팁이 그 자리에 고정됩니다. #weak (기본 설정입니다.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "기타"
 SETTINGS_CATEGORY_TOOLTIPS:0 "툴팁"
 SETTINGS_CATEGORY_SFX:0 "개별 효과음"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "일반"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "지도 조작"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "저장된 게임"
 SETTINGS_CATEGORY_LANGUAGE:0 "언어"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "고급 - 일반"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "고급 - 지도"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "고급 - 인물"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "초상화"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "멀티플레이"
 SETTINGS_CATEGORY_MAP:0 "지도"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "질병 및 부상 그래픽 표시"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\n인물의 초상화에서 부상과 질병 그래픽을 표시할 것인지를 설정합니다."
 SETTING_SHOW_NUDITY:0 "나체 표시"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\n인물의 나체 표시 여부를 설정합니다."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "왕실 궁정 유휴 상태"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\n유휴 상태일 때 왕실 궁정 카메라가 서서히 궁정을 살펴보는 동작을 취하게 할지 결정합니다.\n\n인물 애니메이션이 비활성화 상태라면 해당 설정은 적용되지 않습니다."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "왕실 궁정 부드러운 전환"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\n왕실 궁정 카메라가 새로운 위치로 이동할 때 부드럽게 전환할지를 결정합니다.\n\n인물 애니메이션이 비활성화 상태라면 해당 설정은 적용되지 않습니다."
 NEVER:0 "없음"
 MONTHLY:0 "1달마다"
 HALFYEAR:0 "6달마다"
 YEARLY:0 "1년마다"
 FIVE_YEAR:0 "5년마다"
 SETTINGS_CATEGORY_TUTORIAL:0 "튜토리얼"
 SETTING_REACTIVE_TUTORIAL:1 "상황별 조언 표시"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\n게임 플레이에 반응하는 반응형 튜토리얼 조언을 표시할지 설정합니다. 크루세이더 킹즈 III를 처음 하는 플레이어에게 유용합니다."
 SETTING_SHOW_SUGGESTIONS:0 "제안 표시"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\n일정 시간마다 게임이 무언가를 제안하게 합니다. 크루세이더 킹즈 III를 처음 하는 플레이어에게 유용합니다."
 RESET_REACTIVE_ADVICE:0 "상황별 조언 초기화"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T 상황별 조언 초기화#!\n이전에 본 상황별 조언이 다시 한번 표시됩니다."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "상황별 조언 초기화"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "상황별 조언을 초기화하시겠습니까?"
 SETTING_ADVANCED_SHADERS:0 "고급 셰이더 효과"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T 고급 셰이더 효과\n#!이 설정은 고급 셰이더 효과를 활성화합니다.\n\n이 설정을 끄면 지형, 물과 같은 특정 효과가 저하되는 대신 게임 성능이 향상됩니다."
 SETTING_WINTER_PARTICLE_EFFECTS:0 "겨울 파티클 효과"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\n지도 상의 일부 지역에 겨울이 찾아왔을 경우, 파티클 효과를 적용할지 여부를 결정합니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_RESET_CAMERA_ROTATION:0 "카메라 회전 초기화"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\n사용자가 카메라를 회전시킨 후에, 자동으로 기본 위치로 돌아가게 할지를 결정합니다."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "궁정 화면 배경 인물"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\n왕실 궁정 3D 화면에서 중요성이 떨어지는 배경 인물을 표시할지 결정합니다."
 SETTING_MAP_HIGHLIGHT:0 "지도 커서 강조"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\n지도에서 커서를 얼마나 강조 표시할지를 결정합니다."
 BASED_ON_ZOOM_LEVEL:0 "동적"
 ALWAYS_HIDE:0 "항상 숨김"
 ALWAYS_SHOW:0 "항상 표시"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "해안 국경"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\n이 설정은 해안 국경이 보이는 수준을 조절합니다.\n$BASED_ON_ZOOM_LEVEL$ 단계에서는 화면 확대 정도에 따라 사라지게 됩니다.\n\n$ALWAYS_SHOW$ 또는 $ALWAYS_HIDE$에서는 해안 국경을 동적으로 숨기지 않아 게임 성능을 향상시킬 수 있습니다."
 SETTINGS_DISCARD_CHANGES:0 "변경사항 취소"
