l_russian:
 SETTING_DEBUG_SAVES:0 "Количество сохранений отладки"
 SETTING_TUTORIAL:0 "Обучение"
 SETTING_DISABLED_HINTS:0 "Отключенные подсказки"
 SETTING_FOCUS_ON_COMBAT:0 "Фокус на сражении"
 SETTING_TOOLTIP_DELAY:1 "Задержка всплывающей подсказки"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nЗадержка между появлением всплывающих подсказок."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Задержка разблокировки"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nЗадержка перед разблокировкой всплывающих подсказок."
 SETTING_TOOLTIP_LOCK_TIME:0 "Задержка блокировки"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nЗадержка перед блокировкой всплывающих подсказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Задержка открытия"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nЗадержка перед блокировкой всплывающих подсказок, если одна подсказка уже открыта."
 # Audio
 SETTING_Sound_Effects:1 "Все звуковые эффекты"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Громкость звуковых эффектов\n#!Меняет громкость всех звуковых эффектов."
 SETTING_Ambience:0 "Окружение"
 SETTING_Ambience_TOOLTIP:1 "#T Громкость окружения\n#!Меняет громкость звуков окружающей среды."
 SETTING_TOOLTIP_MODE:1 "Режим всплывающих подсказок"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nСпособ фиксации всплывающих подсказок — для подсказок в подсказках."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Поведение мыши"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nВсплывающие подсказки автоматически фиксируются, пока вы не уберете с них курсор мыши."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Ручной блок"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nНажмите #V среднюю кнопку мыши#!, чтобы заблокировать или разблокировать подсказку."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Блок по таймеру"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nВсплывающие подсказки остаются на месте, если курсор мыши в течение короткого времени остается неподвижным. #weak (По умолчанию)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Разное"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Всплывающие подсказки"
 SETTINGS_CATEGORY_SFX:0 "Особые звуковые эффекты"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Общие"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Управление картой"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Сохранение игры"
 SETTINGS_CATEGORY_LANGUAGE:0 "Язык"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Расширенные"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Расширенные — карта"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Расширенные — персонажи"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Портреты"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Сетевая игра"
 SETTINGS_CATEGORY_MAP:0 "Карта"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Показывать реалистичные раны и следы от болезней"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nОпределяет, будут ли на портретах персонажей появляться реалистичные раны и следы от болезней."
 SETTING_SHOW_NUDITY:0 "Показывать наготу"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nИзображение обнаженных персонажей."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Панорама при бездействии: монарший двор"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nЕсли этот параметр включен, камера во время бездействия плавно скользит по вашему монаршему двору.\n\nНе действует при отключенной анимации персонажей."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Анимированный переход камеры"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nЕсли этот параметр включен, камера плавно перемещается к новой точке.\n\nНе действует при отключенной анимации персонажей."
 NEVER:0 "Никогда"
 MONTHLY:0 "Каждый месяц"
 HALFYEAR:0 "Каждые 6 месяцев"
 YEARLY:0 "Каждый год"
 FIVE_YEAR:0 "Каждые 5 лет"
 SETTINGS_CATEGORY_TUTORIAL:0 "Обучение"
 SETTING_REACTIVE_TUTORIAL:1 "Показывать контекстные советы"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nВключите или отключите советы, реагирующие на то, как вы играете. Они пригодятся новым игрокам в Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Показывать предложения"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nВключите или отключите советы, которые будут появляться через регулярные промежутки времени. Такие подсказки пригодятся новым игрокам в Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Сбросить контекстные советы"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Начать контекстные советы заново#!\nКонтекстные советы, которые уже были показаны, появятся еще раз."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Сбросить контекстные советы"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Вы уверены, что хотите сбросить контекстные советы?"
 SETTING_ADVANCED_SHADERS:0 "Дополнительные эффекты шейдеров"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Дополнительные эффекты шейдеров\n#!Этот параметр включает дополнительные эффекты шейдеров.\n\nПри отключении производительность системы может вырасти, а качество визуальных эффектов (например прорисовка ландшафта и воды) понизится."
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Зимний эффект частиц"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nОпределяет, будет ли показываться эффект частиц на определенных частых карты в зимнее время.\n\nОтключение настройки может повысить производительность"
 SETTING_RESET_CAMERA_ROTATION:0 "Сброс вращения камеры"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nОпределяет, должна ли камера автоматически возвращаться в стандартное положение после поворота игроком"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Фоновые персонажи двора"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nОпределяет, должна ли 3D-сцена монаршего двора включать в себя менее значимых фоновых персонажей."
 SETTING_MAP_HIGHLIGHT:0 "Подсветка курсора на карте"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nОпределяет интенсивность подсветки курсора на карте"
 BASED_ON_ZOOM_LEVEL:0 "Динамические"
 ALWAYS_HIDE:0 "Всегда скрывать"
 ALWAYS_SHOW:0 "Всегда показывать"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Береговые границы"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nЭтот параметр управляет отображением береговых границ державы.\n$BASED_ON_ZOOM_LEVEL$ скрывает их на подробной карте.\n\n$ALWAYS_SHOW$ или $ALWAYS_HIDE$ могут улучшить производительность, но границы не будут автоматически скрываться при приближении."
 SETTINGS_DISCARD_CHANGES:0 "Отменить изменения"
