l_english:
 impart_values.0001.t:0 "Instilling a Lifelong Lesson"
 impart_values.0001.desc:0 "#italic Ah, to be young, full of vim and vigor. The whole world before you, waiting to be discovered. And your own personality, a mystery onto yourself.#!\n\nI find myself musing on the fickleness of youth when in walks [recipient.GetTitledFirstName], my [recipient.Custom('InsultAdjective')] [ROOT.Char.Custom2('RelationToMeShort', recipient)], with [recipient.GetHerHis] usual lack of attentiveness.\n\nSeeing [recipient.GetHerHim] alights something within me: #bold I will teach this child a lesson in what's important in life.#!"
 already_imparted_lesson_desc:0 "You've already attempted to teach [CHARACTER.GetShortUINameNoTooltip] what to value in life."
 impart_values.0001.diligent:0 "[recipient.GetSheHe] will learn that persistent hard work will always aid them."
 impart_values.0001.lazy:0 " [recipient.GetFirstName] needs to learn to let other people handle things."
 impart_values.0001.cynical:0 "[recipient.GetSheHe] needs to learn to always question the motives of others."
 impart_values.0001.zealous:0 "I will teach [recipient.GetHerHim] that faith is of paramount importance."
 impart_values.0001.brave:0 "[recipient.GetFirstName] will learn to be fearless against any adversary."
 impart_values.0001.craven:0 "To hide away from all fears is a wise lesson to heed."
 impart_values.0001.calm:0 "I will impart upon [recipient.GetFirstName] the importance of staying calm."
 impart_values.0001.wrathful:0 "To be driven by anger and fury is what I will teach [recipient.GetHerHim]."
 impart_values.0001.chaste:0 "[recipient.GetFirstName] should shun away any temptation of natural desires."
 impart_values.0001.lustful:0 "[recipient.GetFirstName] should learn to embrace their natural desires."
 impart_values.0001.content:0 "I will teach [recipient.GetHerHim] to be contented with what [recipient.GetHerHim] already possesses."
 impart_values.0001.ambitious:0 "I will teach [recipient.GetHerHim] the importance of ambition."
 impart_values.0001.fickle:0 "I will teach [recipient.GetHerHim] that a changing mind is a desirable trait."
 impart_values.0001.stubborn:0 "[recipient.GetSheHe] will be taught to never back down against any opposition."
 impart_values.0001.forgiving:0 "[recipient.GetSheHe] will learn the importance of showing mercy to others."
 impart_values.0001.vengeful:0 "I will teach [recipient.GetHerHim] to never forget the people who wrong them."
 impart_values.0001.generous:0 "I will show [recipient.GetHerHim] that acts of charity are endlessly meaningful."
 impart_values.0001.greedy:0 "A tight grip on ones purse is always a fine lesson to learn."
 impart_values.0001.gregarious:0 "I will show [recipient.GetHerHim] the joys of the company of others."
 impart_values.0001.shy:0 "I will teach [recipient.GetHerHim] the peaceful benefits of being alone."
 impart_values.0001.honest:0 "[recipient.GetSheHe] will learn that truth and sincerity are primary values."
 impart_values.0001.deceitful:0 "I will teach [recipient.GetFirstName] to lie as easily as breath."
 impart_values.0001.humble:0 "A life of modesty is a simple pleasure for [recipient.GetFirstName] to learn."
 impart_values.0001.arrogant:0 "[recipient.GetSheHe] will learn that their sense of self worth is above all else."
 impart_values.0001.just:0 "I will teach [recipient.GetHerHim] to abide by the laws of gods and men."
 impart_values.0001.arbitrary:0 "They should learn to do their own thing, regardless of others."
 impart_values.0001.patient:0 "The importance of patience is what I will impart upon [recipient.GetHerHim]."
 impart_values.0001.impatient:0 "I will teach [recipient.GetHerHim] to become restless at delay of seeing results."
 impart_values.0001.temperate:0 "[recipient.GetSheHe] will learn that everything should be taken in moderation."
 impart_values.0001.gluttonous:0 "[recipient.GetFirstName] should shower in abundance of all things pleasurable."
 impart_values.0001.trusting:0 "[recipient.GetSheHe] will learn to trust those around [recipient.GetHerHim]."
 impart_values.0001.paranoid:0 "[recipient.GetFirstName] must learn to watch their back at all times."
 impart_values.0001.compassionate:0 "[recipient.GetFirstName] shall be taught compassion above all else."
 impart_values.0001.callous:0 "Disregarding others problems will serve [recipient.GetFirstName] well."
 impart_values.0001.sadistic:0 "I will teach [recipient.GetHerHim] the pleasure to be had in hurting others."
 impart_values.0001.rude:0 "I will teach [recipient.GetHerHim] to speak their mind no matter how blunt."
 impart_values.0001.honorable:0 "I shall teach [recipient.GetFirstName] to hold their morals in high esteem."
 impart_values.0001.ruthless:0 "[recipient.GetSheHe] will learn to be merciless in order to achieve their goals."
 impart_values.0001.authoritative:0 "I will teach [recipient.GetHerHim] the importance of being authoritative."
 impart_values.0001.backout:0 "Never mind, I don't think [recipient.GetSheHe] is ready."
 impart_values_lesson_ignored_title:0 "Lesson Ignored"
 impart_values_lesson_ignored_desc:0 "[recipient.GetShortUINameNoTooltip] showed no interest in your lessons."
 impart_values_lesson_success_title:0 "Lesson Success"
 impart_values_lesson_success_desc:0 "[recipient.GetShortUINameNoTooltip] has taken your lessons to heart and gained the [recipient.Custom('TraitLearned')] trait."
 impart_values_lesson_failure_title:0 "Lesson Failure"
 impart_values_lesson_failure_desc:0 "[recipient.GetShortUINameNoTooltip] has revolted against your lessons and gained the [recipient.Custom('TraitLearned')] trait."